# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Based on EM algorithm and boot algorithm, the survival analysis of censored data was carried out
#' @description Based on EM algorithm and boot algorithm, the survival analysis of censored data was carried out
#' @param x the results of the first type of experiment
#' @param s cut-off values in the first type of experiment
#' @param y the results of the second type of experiment
#' @param u the results of the third type of experiment
#' @param v the results of the third type of experiment
#' @param lambda0 the initial value of the iteration
#' @param max.it the maximum number of iterations
#' @param lambda parameters of the survival model
#' @param B number of bootstrap samples
#' @param alpha the level of significance of the confidence interval
#' @return  a list with maximum likelihood estimates for parameters, full values for censored data, and estimated expectations, variances, and confidence intervals
#' @export
EMcpp <- function(x, s, y, u, v, lambda0 = 0.1, max_it = 1e4L, tol = 1e-6) {
    .Call('_SA23204158_EMcpp', PACKAGE = 'SA23204158', x, s, y, u, v, lambda0, max_it, tol)
}

Supvaluecpp <- function(x, s, y, u, v, lambda) {
    .Call('_SA23204158_Supvaluecpp', PACKAGE = 'SA23204158', x, s, y, u, v, lambda)
}

